### ISSUE TITLE
Link to Paper?

### ISSUE THREAD

**Issue by peterdsharpe** [wilson-labs/cola#10]
Hey all,

The [README.md](https://github.com/wilson-labs/cola/blob/main/README.md#Citing-us) references a pre-print paper, but the hyperlink provided seems to just point back to the main GitHub repo rather than link to the actual paper. Is this pre-print available somewhere online to read?

Thanks!

**Comment by mfinzi** [comment]
Hi @peterdsharpe ,
We have not yet released our paper on Arxiv, but we are planning on uploading along with a public release of our library within the next two weeks. Stay tuned :)

**Comment by peterdsharpe** [comment]
Sounds good, looking forward to reading it! If you can, I'd appreciate a ping via this issue ticket when the paper goes live!

**Comment by mfinzi** [comment]
Hey @peterdsharpe, maybe we can send you the preprint via email for now? Is pds@mit.edu a good address?

**Comment by peterdsharpe** [comment]
That would be great! That email address is best - thanks so much!

**Comment by AndPotap** [comment]
Hey @peterdsharpe, sorry for the delay. Here is the link https://arxiv.org/abs/2309.03060
