### ISSUE TITLE
[Feature Request] versioning + PyPI pip wheel

### ISSUE THREAD

**Issue by daniel-dodd** [wilson-labs/cola#23]
# 🚀 Feature Request

Great work on this library! :)

A couple of requests from the GPJax developers:

(1) PyPI pip wheel for installation.
(2) Using git tags & creating versioned releases on GitHub, with corresponding releases made to PyPI.

Versioning would particularly make it easier to monitor incoming developmental changes.

**Comment by mfinzi** [comment]
Yes, we will do this right away. @AndPotap, shall we plan to upload a release at the end of today?

**Comment by AndPotap** [comment]
Hey, just added an [alpha release](https://github.com/wilson-labs/cola/releases/tag/v0.0.1) :wink:

**Comment by daniel-dodd** [comment]
Thanks @mfinzi, @AndPotap for sorting this so quickly! 😊
