### ISSUE TITLE
[Feature Request]  Structured Cholesky decomposition for linear operators

### ISSUE THREAD

**Issue by daniel-dodd** [wilson-labs/cola#30]
# 🚀 Feature Request

Add efficient Cholesky decomposition rules for structured linear operators.

## Motivation
Presently we can use `cola.decompositions.cholesky_decomposed` to receive a "lazy product" of two upper and lower triangular linear operators.

```python
def cholesky_decomposed(A: LinearOperator):
    """ Performs a cholesky decomposition A=LL* of a linear operator A.
        The returned operator LL* is the same as A, but represented using
        the triangular structure """
    L = Triangular(A.xnp.cholesky(A.to_dense()), lower=True)
    return L @ L.H
```

This is really neat, however currently only assumes a dense structure. 

For e.g., a diagonal linear operator, the lower cholesky decomposition can be more efficiently computed, simply taking the root of the diagonal. Moreover, this would be critical for efficiency e.g., with Kronecker products structures.

## Pitch

**Describe the solution you'd like**

- Add e.g., a dispatch rule to `cholesky_decomposed` to provide better efficiency for structured `LinearOperator`'s, with "dense" assumption as a fallback.

**Are you willing to open a pull request?** (We LOVE contributions!!!)
Happy to help. :)

**Comment by mfinzi** [comment]
Absolutely, we can do that. The existing implementation can serve as the base case.

For which LinearOperators does it make sense to have rule? We've been thinking more about about the rules for the basic linalg operations, but for cholesky the ones that come to mind are:

- Diag
- BlockDiag
- Identity, ScalarMul
- Triangular? (What should the desired behavior be here?)
- Kronecker (just kron of the Cholesky's right?)

What else?

**Comment by daniel-dodd** [comment]
Fantastic! Thanks for the quick reply. This would be really cool. :) 

Yeah at the bare minimum to prioritise getting cola into GPJax we would like to see `Diag`, `Identity`, `ScalarMul` in addition to `Dense`, perhaps as a quick PR. Which I would be happy to do.

The others would be nice to have soon too! We are e.g., looking to do some `Kronecker` stuff shortly too, so a Cholesky would be handy here too (e.g., for whitening in the non-conjugate GP setting). I suppose some others would be:

- `Tridiagonal` (e.g., when doing Kalman filters).
- `Toeplitz` (e.g., my Kernel is stationary and my data is on a grid).

I think for the `Triangular` I would expect to see an error as it is not a PSD matrix - and there is nothing to decompose?

**Comment by mfinzi** [comment]
Yeah that sounds good, of course you're right `Triangular` should just raise an error in that case (presumably it will be caught by the Cholesky base case erroring due to singular factors). 

For some of these other types like Tridiagonal and Toeplitz, is there an algorithm or simplification rule you had in mind for efficiently computing these decompositions? For a couple of these (Tridiagonal and Toeplitz are good examples), we have known rules to add for speeding up eigen decomposition and inversion/solves that we have not yet added, but I'm not as familiar with how this should look for the Cholesky or LU decompositions.

**Comment by daniel-dodd** [comment]
Wow thank you that was quick! :)

**Comment by daniel-dodd** [comment]
@mfinzi would appreciate if you could push a v`0.0.2` release for this?
