### ISSUE TITLE
[Feature Request] Hutch++ trace estimator

### ISSUE THREAD

**Issue by mfinzi** [wilson-labs/cola#47]
# 🚀 Feature Request

An implementation of the [Hutch++ trace and diagonal estimator](https://arxiv.org/abs/2010.09649)

## Motivation

The $1/\sqrt{n}$ convergence of the Hutchinson estimator can be very slow and it would be nice to have some alternative algorithms here

## Pitch

Implementation going in here:
https://github.com/wilson-labs/cola/tree/main/cola/algorithms
and to be wired up into the `cola.linalg.trace` and `cola.linalg.diag` function via the method arguments

**Comment by Fr0do** [comment]
If we want to follow the original algorithm, option for Rademacher distribution should be available. It's possible to use ```xnp.sign(xnp.randn(...))```, but adding ```xnp.rand``` to backends would make it less ambiguous.

**Comment by AndPotap** [comment]
Doing some house keeping . I'm closing this as we have [`HutchPP`](https://github.com/wilson-labs/cola/blob/main/cola/linalg/trace/diagonal_estimation.py#L59-L82). Thank you both for the discussion and code changes.
