### ISSUE TITLE
Requirements files

### ISSUE THREAD

**Issue by activatedgeek** [wilson-labs/cola#5]
It will probably be easier to maintain two different requirements files: `requirements.txt` and `requirements.dev.txt` for the production package and development package respectively.

I see that you have a `requirements.sh` which seems to have commands for different CUDA versions. I think the users can be referred to the respective dependency doc and remove the burden from CoLA to explain those details.

In the final requirements.txt, you can keep un-versioned PyTorch/JAX so that it doesn't interfere with the dependency parsing as long it is installed.

When published to PyPI, the user installs can look like:
```
pip install cola
```

and the development installs can look like:
```
pip install cola[dev]
```

(this can be achieved by using the `extras_require: { "dev": ["pytest", ...] }` in the `setuptools` configuration (just like the `install_requires` list).

**Comment by mfinzi** [comment]
definitely. We should move pytest to the optional [dev] dependency and add in the appropriate version of jax and pytorch. (requirement.sh is not meant to be run at the moment)
